<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis" Version="5.3.0"/>
        <PackageReference Include="uml4net.HandleBars" Version="8.2.1"/>
        <PackageReference Include="uml4net.xmi" Version="8.2.1"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="Templates\Uml\dto-class-uml-template.hbs">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Templates\Uml\dto-interface-uml-template.hbs">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Templates\Uml\enumeration-uml-template.hbs">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    
</Project>
