<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Description>The code generator for the Mycelium SDK.</Description>
        <Company>Starion Group S.A.</Company>
        <Copyright>Copyright © Starion Group S.A.</Copyright>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/mycelium-cmbse/mycelium-sdk.git</RepositoryUrl>
        <RepositoryType>Git</RepositoryType>
        <Authors>Sam Gerene, Antoine Théate, Régis André, Tanase-Marius Manafu, Omrane Haj Mohamed</Authors>
        <IsPackable>false</IsPackable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis" Version="5.3.0"/>
        <PackageReference Include="uml4net.HandleBars" Version="8.3.0" />
        <PackageReference Include="uml4net.xmi" Version="8.3.0" />
    </ItemGroup>

    <ItemGroup>
        <None Update="Templates\Uml\dto-class-uml-template.hbs">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Templates\Uml\dto-interface-uml-template.hbs">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Templates\Uml\enumeration-uml-template.hbs">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Templates\Uml\poco-interface-uml-template.hbs">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Templates\Uml\poco-class-uml-template.hbs">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    
</Project>
