// <auto-generated />
// ------------------------------------------------------------------------------------------------
//  <copyright file="IElementNavigationService.cs" company="Starion Group S.A.">
//
//    Copyright 2026 Starion Group S.A.
//    SPDX-License-Identifier: Apache-2.0
//
//  </copyright>
//  ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Fabric.ConcurrentServer.Services
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    using ErrorOr;

    using SysML2.NET.PIM;
    using SysML2.NET.PIM.DTO;
    using SysML2.NET.PSM;

    /// <summary>
    /// Defines the ElementNavigationService of the OMG Systems Modeling API and Services specification, §7.2.2.
    /// </summary>
    [GeneratedCode("Mycelium.SDK", "latest")]
    public partial interface IElementNavigationService : IBaseService
    {
        /// <summary>
        /// Get element with the given id (elementId) in the given project at the given commit.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="commitId">
        /// The identifier of the commit.
        /// </param>
        /// <param name="elementId">
        /// The elementId.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<SysML2.NET.Core.DTO.Root.Elements.IElement>> GetElementByIdAsync(Guid projectId, Guid commitId, Guid elementId, CancellationToken cancellationToken);

        /// <summary>
        /// Get all the elements in a given project at the given commit.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="commitId">
        /// The identifier of the commit.
        /// </param>
        /// <param name="queryParameters">
        /// The paging parameters applied to the result.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<PagedResult<SysML2.NET.Core.DTO.Root.Elements.IElement>>> GetElementsAsync(Guid projectId, Guid commitId, QueryParameters queryParameters, CancellationToken cancellationToken);

        /// <summary>
        /// Get relationships that are incoming, outgoing, or both relative to the given related element.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="commitId">
        /// The identifier of the commit.
        /// </param>
        /// <param name="elementId">
        /// The elementId.
        /// </param>
        /// <param name="direction">
        /// The direction.
        /// </param>
        /// <param name="queryParameters">
        /// The paging parameters applied to the result.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<PagedResult<SysML2.NET.Core.DTO.Root.Elements.IRelationship>>> GetRelationshipsByRelatedElementAsync(Guid projectId, Guid commitId, Guid elementId, Direction direction, QueryParameters queryParameters, CancellationToken cancellationToken);

        /// <summary>
        /// Get all the root elements in the given project at the given commit.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="commitId">
        /// The identifier of the commit.
        /// </param>
        /// <param name="queryParameters">
        /// The paging parameters applied to the result.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<PagedResult<SysML2.NET.Core.DTO.Root.Elements.IElement>>> GetRootElementsAsync(Guid projectId, Guid commitId, QueryParameters queryParameters, CancellationToken cancellationToken);
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
