// <auto-generated />
// ------------------------------------------------------------------------------------------------
//  <copyright file="IExternalRelationshipService.cs" company="Starion Group S.A.">
//
//    Copyright 2026 Starion Group S.A.
//    SPDX-License-Identifier: Apache-2.0
//
//  </copyright>
//  ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Fabric.ConcurrentServer.Services
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    using ErrorOr;

    using SysML2.NET.PIM;
    using SysML2.NET.PIM.DTO;
    using SysML2.NET.PSM;

    /// <summary>
    /// Defines the ExternalRelationshipService of the OMG Systems Modeling API and Services specification, §7.2.5.
    /// </summary>
    [GeneratedCode("Mycelium.SDK", "latest")]
    public partial interface IExternalRelationshipService : IBaseService
    {
        /// <summary>
        /// Create an external relationship in a given project on a given branch.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="branchId">
        /// The identifier of the branch.
        /// </param>
        /// <param name="externalRelationship">
        /// The externalRelationship.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Success>> CreateExternalRelationshipAsync(Guid projectId, Guid? branchId, ExternalRelationship externalRelationship, CancellationToken cancellationToken);

        /// <summary>
        /// Delete the external relationship with the given id (externalRelationshipId).
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="branchId">
        /// The identifier of the branch.
        /// </param>
        /// <param name="externalRelationshipId">
        /// The externalRelationshipId.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Success>> DeleteExternalRelationshipAsync(Guid projectId, Guid? branchId, Guid externalRelationshipId, CancellationToken cancellationToken);

        /// <summary>
        /// Get the external relationship with the given id (externalRelationshipId).
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="commitId">
        /// The identifier of the commit.
        /// </param>
        /// <param name="externalRelationshipId">
        /// The externalRelationshipId.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<ExternalRelationship>> GetExternalRelationshipByIdAsync(Guid projectId, Guid commitId, Guid externalRelationshipId, CancellationToken cancellationToken);

        /// <summary>
        /// Get all the external relationships in a given project at a given commit.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="commitId">
        /// The identifier of the commit.
        /// </param>
        /// <param name="queryParameters">
        /// The paging parameters applied to the result.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<PagedResult<ExternalRelationship>>> GetExternalRelationshipsAsync(Guid projectId, Guid commitId, QueryParameters queryParameters, CancellationToken cancellationToken);

        /// <summary>
        /// Get all the external relationships in the given project at the given commit, where the id of
        /// elementEnd of the external relationship is the given elementId.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="commitId">
        /// The identifier of the commit.
        /// </param>
        /// <param name="elementId">
        /// The elementId.
        /// </param>
        /// <param name="queryParameters">
        /// The paging parameters applied to the result.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<PagedResult<ExternalRelationship>>> GetExternalRelationshipsByElementAsync(Guid projectId, Guid commitId, Guid elementId, QueryParameters queryParameters, CancellationToken cancellationToken);
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
