// <auto-generated />
// ------------------------------------------------------------------------------------------------
//  <copyright file="IProjectService.cs" company="Starion Group S.A.">
//
//    Copyright 2026 Starion Group S.A.
//    SPDX-License-Identifier: Apache-2.0
//
//  </copyright>
//  ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Fabric.ConcurrentServer.Services
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    using ErrorOr;

    using SysML2.NET.PIM;
    using SysML2.NET.PIM.DTO;
    using SysML2.NET.PSM;

    /// <summary>
    /// Defines the ProjectService of the OMG Systems Modeling API and Services specification, §7.2.1.
    /// </summary>
    [GeneratedCode("Mycelium.SDK", "latest")]
    public interface IProjectService : IBaseService
    {
        /// <summary>
        /// Create a new project with the given name and description (optional).
        /// </summary>
        /// <param name="name">
        /// The name.
        /// </param>
        /// <param name="description">
        /// The description.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Project>> CreateProjectAsync(string name, string description, CancellationToken cancellationToken);

        /// <summary>
        /// Delete the project with the given id (projectId).The following pre-condition must be satisfied for a
        /// project to be deleted.<ol> <li>Project with given projectId exists.</li></ol>The following
        /// post-condition must be satisfied for a project to be deleted.<ol> <li>All operations of all services
        /// where projectId (Id of the deleted project) is an input argument will return null.</li></ol>Note
        /// that when a project is being deleted, elements owned by the project may be used in other projects
        /// via project usages. The detection of this condition and subsequent behavior is left to the API and
        /// Service providers. As a general recommendation, API and Service providers may implement different
        /// behaviors, such as, but not limited to, the following.<ol> <li>Allow projects to be deleted
        /// irrespective of any of the elements from its latest tag (commit), default or pre-specified branches,
        /// being used in other projects, via project usages. The Service provider guarantees that future
        /// operations involving the using projects will continue to work in the absence of referenced elements
        /// owned by the deleted project. It is up to the Service Provider to find a way to implement this
        /// guarantee, such as by suppressing such nonexistent element references or reporting only unique
        /// identifiers of nonexistent element references in operation results.</li> <li>Allow projects to be
        /// deleted only if none of the elements in a list of pre-specified commits (e.g. latest tag and main
        /// branch) are being used in the list of pre-specified commits (e.g. latest tag or main branch) of
        /// another project, via project usage.</li> <li>Allow projects to be deleted only if none of their
        /// commits are referenced by project usages in any of the commits of any other project.</li></ol>
        /// </summary>
        /// <param name="projectId">
        /// The projectId.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Project>> DeleteProjectAsync(Guid projectId, CancellationToken cancellationToken);

        /// <summary>
        /// Get project with the given id (projectId).
        /// </summary>
        /// <param name="projectId">
        /// The projectId.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Project>> GetProjectByIdAsync(Guid projectId, CancellationToken cancellationToken);

        /// <summary>
        /// Get all projects.
        /// </summary>
        /// <param name="queryParameters">
        /// The paging parameters applied to the result.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<PagedResult<Project>>> GetProjectsAsync(QueryParameters queryParameters, CancellationToken cancellationToken);

        /// <summary>
        /// Update the project with the given id (projectId).
        /// </summary>
        /// <param name="projectId">
        /// The projectId.
        /// </param>
        /// <param name="name">
        /// The name.
        /// </param>
        /// <param name="description">
        /// The description.
        /// </param>
        /// <param name="defaultBranchId">
        /// The identifier of the defaultBranch.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Project>> UpdateProjectAsync(Guid projectId, string name, string description, Guid? defaultBranchId, CancellationToken cancellationToken);
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
