// <auto-generated />
// ------------------------------------------------------------------------------------------------
//  <copyright file="IProjectDataVersioningService.cs" company="Starion Group S.A.">
//
//    Copyright 2026 Starion Group S.A.
//    SPDX-License-Identifier: Apache-2.0
//
//  </copyright>
//  ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Fabric.ConcurrentServer.Services
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    using ErrorOr;

    using SysML2.NET.PIM;
    using SysML2.NET.PIM.DTO;
    using SysML2.NET.PSM;

    /// <summary>
    /// Defines the ProjectDataVersioningService of the OMG Systems Modeling API and Services specification, §7.2.3.
    /// </summary>
    [GeneratedCode("Mycelium.SDK", "latest")]
    public partial interface IProjectDataVersioningService : IBaseService
    {
        /// <summary>
        /// Create a new branch with the given name (branchName) in the given project, and set the head of the
        /// new branch as the given commit (head).
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="branchName">
        /// The branchName.
        /// </param>
        /// <param name="headId">
        /// The identifier of the head.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Branch>> CreateBranchAsync(Guid projectId, string branchName, Guid headId, CancellationToken cancellationToken);

        /// <summary>
        /// Create a new commit with the given change (collection of DataVersion records) in the given branch of
        /// the project. If the branch is not specified, the default branch of the project is used.
        /// Commit.change should include the following for each Data object that needs to be created, updated,
        /// or deleted in the new commit. (1) Creating Data - Commit.change should include a DataVersion record
        /// with DataVersion.payload populated with the Data being created. DataVersion.identity is either left
        /// empty, in which case a new DataIdentity needs to be created by the Service and assigned to
        /// DataVersion.identity in the new commit; or provided a brand new value (one that does not already
        /// exist in any of the previousCommits) by the client and accepted by the Service as is. (2) Updating
        /// Data - Commit.change should include a DataVersion record with DataVersion.payload populated with the
        /// updated Data. DataVersion.identity should be populated with the DataIdentity for which a new
        /// DataVersion record will be created in the new commit. (3) Deleting Data - Commit.change should
        /// include a DataVersion record with DataVersion.payload not provided, thereby indicating deletion of
        /// DataIdentity in the new commit. DataVersion.identity should be populated with the DataIdentity that
        /// will be deleted in the new commit. When a DataIdentity is deleted in a commit, all its versions
        /// (DataVersion) are also deleted, and any references from other DataIdentity are also removed to
        /// maintain data integrity. In addition, for Element Data (KerML), deletion of an Element must also
        /// result in deletion of incoming Relationships. When Element Data (KerML) is created or updated,
        /// derived properties must be computed or verified if the API provider claims Derived Property
        /// Conformance. The deleted element - DataIdentity and its DataVersion records - will be accessible in
        /// previous commits.
        /// </summary>
        /// <param name="change">
        /// The change elements.
        /// </param>
        /// <param name="branchId">
        /// The identifier of the branch.
        /// </param>
        /// <param name="previousCommitsIds">
        /// The identifier of the previousCommits elements.
        /// </param>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Commit>> CreateCommitAsync(IReadOnlyList<DataVersion> change, Guid? branchId, IReadOnlyList<Guid> previousCommitsIds, Guid projectId, CancellationToken cancellationToken);

        /// <summary>
        /// Create a new tag with the given name (tagName) in the given project, and set the taggedCommit of the
        /// new tag as the given commit (taggedCommit).
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="tagName">
        /// The tagName.
        /// </param>
        /// <param name="taggedCommitId">
        /// The identifier of the taggedCommit.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Tag>> CreateTagAsync(Guid projectId, string tagName, Guid taggedCommitId, CancellationToken cancellationToken);

        /// <summary>
        /// Delete the branch with the given id (branchId) in the given project.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="branchId">
        /// The branchId.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Branch>> DeleteBranchAsync(Guid projectId, Guid branchId, CancellationToken cancellationToken);

        /// <summary>
        /// Delete the tag with the given id (tadId) in the given project.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="tagId">
        /// The tagId.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Tag>> DeleteTagAsync(Guid projectId, Guid tagId, CancellationToken cancellationToken);

        /// <summary>
        /// Get the difference between two commits - compareCommit and baseCommit. The set of all DataVersion
        /// records in a project at a given commit is accessible as Commit.versionedData. From a set theoretic
        /// perspective, this operation gets compareCommit.versionedData - baseCommit.versionedData and
        /// returns a DataDifference object with baseData and compareData for each difference. If any data is
        /// present in the compareCommit but absent in the baseCommit, DataDifference.compareData will include
        /// the corresponding DataVersion and DataDifference.baseData will be empty. If any data is absent in
        /// the compareCommit but present in the baseCommit, DataDifference.compareData will be empty and
        /// DataDifference.baseData will include the corresponding DataVersion. If any data is present in both
        /// but different in the compareCommit and baseCommit, DataDifference.compareData and
        /// DataDifference.baseData will include the corresponding DataVersion records.The operation diffCommits
        /// in ProjectDataVersioningService has an optional argument changeTypes that is a collection typed by
        /// the enumeration ChangeType with three literals (CREATED, UPDATED, DELETED).If the argument
        /// changeTypes is passed, then only the changes of the given type will be returned by the operation as
        /// DataDifference objects. Some examples to elaborate this behavior are included below.If changeTypes =
        /// [], i.e. the argument is not specified, then the DataDifference objects for all the data that was
        /// created, updated, or deleted in the compareCommit versus the baseCommit will be returned.If
        /// changeTypes = ['DELETED'], then the DataDifference objects for all the data that was deleted in the
        /// compareCommit versus the baseCommit will be returned. If changeTypes = ['CREATED', 'UPDATED'], then
        /// the DataDifference objects for all the data that was created or updated in the compareCommit versus
        /// the baseCommit will be returned.
        /// </summary>
        /// <param name="baseCommitId">
        /// The identifier of the baseCommit.
        /// </param>
        /// <param name="compareCommitId">
        /// The identifier of the compareCommit.
        /// </param>
        /// <param name="changeTypes">
        /// The changeTypes elements.
        /// </param>
        /// <param name="queryParameters">
        /// The paging parameters applied to the result.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<PagedResult<DataDifference>>> DiffCommitsAsync(Guid baseCommitId, Guid compareCommitId, IReadOnlyList<ChangeType> changeTypes, QueryParameters queryParameters, CancellationToken cancellationToken);

        /// <summary>
        /// Get the branch with the given id (branchId) in the given project.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="branchId">
        /// The branchId.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Branch>> GetBranchByIdAsync(Guid projectId, Guid branchId, CancellationToken cancellationToken);

        /// <summary>
        /// Get all the branches in the given project.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="queryParameters">
        /// The paging parameters applied to the result.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<PagedResult<Branch>>> GetBranchesAsync(Guid projectId, QueryParameters queryParameters, CancellationToken cancellationToken);

        /// <summary>
        /// Get the commit with the given id (commitId) in the given project.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="commitId">
        /// The commitId.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Commit>> GetCommitByIdAsync(Guid projectId, Guid commitId, CancellationToken cancellationToken);

        /// <summary>
        /// Get the change in the given commit of the given project.The operation getCommitChange in
        /// ProjectDataVersioningService has an optional argument changeTypes that is a collection typed by the
        /// enumeration ChangeType with three literals (CREATED, UPDATED, DELETED).If the argument changeTypes
        /// is passed, then only the changes of the given type will be returned by the operation as DataVersion
        /// records. Some examples to elaborate this behavior are included below.If changeTypes = [], i.e. the
        /// argument is not specified, then the DataVersion records for all the data that was created, updated,
        /// or deleted in the given commit will be returned.If changeTypes = ['DELETED'], then the DataVersion
        /// records for all the data that was deleted in the given commit will be returned.If changeTypes =
        /// ['CREATED', 'UPDATED'], then the DataVersion records for all the data that was created or updated in
        /// the given commit will be returned.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="commitId">
        /// The identifier of the commit.
        /// </param>
        /// <param name="changeTypes">
        /// The changeTypes elements.
        /// </param>
        /// <param name="queryParameters">
        /// The paging parameters applied to the result.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<PagedResult<DataVersion>>> GetCommitChangeAsync(Guid projectId, Guid commitId, IReadOnlyList<ChangeType> changeTypes, QueryParameters queryParameters, CancellationToken cancellationToken);

        /// <summary>
        /// Get the change with the given id (changeId) in the given commit of the given project. The changeId
        /// is the id of the DataVersion that changed in the commit.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="commitId">
        /// The identifier of the commit.
        /// </param>
        /// <param name="changeId">
        /// The changeId.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<DataVersion>> GetCommitChangeByIdAsync(Guid projectId, Guid commitId, Guid changeId, CancellationToken cancellationToken);

        /// <summary>
        /// Get all the commits in the given project.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="queryParameters">
        /// The paging parameters applied to the result.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<PagedResult<Commit>>> GetCommitsAsync(Guid projectId, QueryParameters queryParameters, CancellationToken cancellationToken);

        /// <summary>
        /// Get the default branch of the given project.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Branch>> GetDefaultBranchAsync(Guid projectId, CancellationToken cancellationToken);

        /// <summary>
        /// Get the head commit of the given branch in the given project. If the branch is not specified, the
        /// default branch of the project is used.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="branchId">
        /// The identifier of the branch.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Commit>> GetHeadCommitAsync(Guid projectId, Guid? branchId, CancellationToken cancellationToken);

        /// <summary>
        /// Get the tag with the given id (tagId) in the given project.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="tagId">
        /// The tagId.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Tag>> GetTagByIdAsync(Guid projectId, Guid tagId, CancellationToken cancellationToken);

        /// <summary>
        /// Get the tagged commit of the given tag in the given project.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="tagId">
        /// The identifier of the tag.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Commit>> GetTaggedCommitAsync(Guid projectId, Guid tagId, CancellationToken cancellationToken);

        /// <summary>
        /// Get all the tags in the given project.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="queryParameters">
        /// The paging parameters applied to the result.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<PagedResult<Tag>>> GetTagsAsync(Guid projectId, QueryParameters queryParameters, CancellationToken cancellationToken);

        /// <summary>
        /// Merge the given commits (commitsToMerge) in the given branch (baseBranch). The commits included in
        /// commitsToMerge may be commits referenced by a CommitReference, such as Branch.head or
        /// Tag.taggedCommit, or any other commit in the owning project (Project.commits).This operation returns
        /// a MergeResult which will include either of the following: (1) commit after the merge operation if
        /// successful, or (2) a set of DataIdentity records representing the merge conflicts if the merge
        /// operation is unsuccessful.Two optional inputs may be provided: (1) resolution as a set of Data that
        /// will resolve the merge conflicts, and (2) description of the merged commit if this operation is
        /// successful.
        /// </summary>
        /// <param name="baseBranchId">
        /// The identifier of the baseBranch.
        /// </param>
        /// <param name="commitsToMergeIds">
        /// The identifier of the commitsToMerge elements.
        /// </param>
        /// <param name="resolution">
        /// The resolution elements.
        /// </param>
        /// <param name="description">
        /// The description.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<MergeResult>> MergeIntoBranchAsync(Guid baseBranchId, IReadOnlyList<Guid> commitsToMergeIds, IReadOnlyList<SysML2.NET.Common.IData> resolution, string description, CancellationToken cancellationToken);

        /// <summary>
        /// Set the branch with the given branchId as the default branch of the given project.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="branchId">
        /// The branchId.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Project>> SetDefaultBranchAsync(Guid projectId, Guid branchId, CancellationToken cancellationToken);
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
