// <auto-generated />
// ------------------------------------------------------------------------------------------------
//  <copyright file="IProjectUsageService.cs" company="Starion Group S.A.">
//
//    Copyright 2026 Starion Group S.A.
//    SPDX-License-Identifier: Apache-2.0
//
//  </copyright>
//  ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Fabric.ConcurrentServer.Services
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    using ErrorOr;

    using SysML2.NET.PIM;
    using SysML2.NET.PIM.DTO;
    using SysML2.NET.PSM;

    /// <summary>
    /// Defines the ProjectUsageService of the OMG Systems Modeling API and Services specification, §7.2.6.
    /// </summary>
    [GeneratedCode("Mycelium.SDK", "latest")]
    public partial interface IProjectUsageService : IBaseService
    {
        /// <summary>
        /// Create a new project usage in the given project at the head commit of the given branch. This
        /// operation returns a new commit that includes the new project usage, and sets the head of the given
        /// branch to the new commit. If a project branch is not given, then the default branch of the project
        /// will be used.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="branchId">
        /// The identifier of the branch.
        /// </param>
        /// <param name="projectUsage">
        /// The projectUsage.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Commit>> CreateProjectUsageAsync(Guid projectId, Guid? branchId, ProjectUsage projectUsage, CancellationToken cancellationToken);

        /// <summary>
        /// Deletes the project usage with the given id (projectUsageId) from the given project at the head
        /// commit of the given branch. This operation returns a new commit where the given project usage does
        /// not exist, and sets the head of the given branch to the new commit. If a project branch is not
        /// given, then the default branch of the project will be used.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="branchId">
        /// The identifier of the branch.
        /// </param>
        /// <param name="projectUsageId">
        /// The projectUsageId.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Commit>> DeleteProjectUsageAsync(Guid projectId, Guid? branchId, Guid projectUsageId, CancellationToken cancellationToken);

        /// <summary>
        /// Get all the project usages in the given project at the given commit.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="commitId">
        /// The identifier of the commit.
        /// </param>
        /// <param name="queryParameters">
        /// The paging parameters applied to the result.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<PagedResult<ProjectUsage>>> GetProjectUsagesAsync(Guid projectId, Guid commitId, QueryParameters queryParameters, CancellationToken cancellationToken);
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
