// <auto-generated />
// ------------------------------------------------------------------------------------------------
//  <copyright file="IQueryService.cs" company="Starion Group S.A.">
//
//    Copyright 2026 Starion Group S.A.
//    SPDX-License-Identifier: Apache-2.0
//
//  </copyright>
//  ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Fabric.ConcurrentServer.Services
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    using ErrorOr;

    using SysML2.NET.PIM;
    using SysML2.NET.PIM.DTO;
    using SysML2.NET.PSM;

    /// <summary>
    /// Defines the QueryService of the OMG Systems Modeling API and Services specification, §7.2.4.
    /// </summary>
    [GeneratedCode("Mycelium.SDK", "latest")]
    public partial interface IQueryService : IBaseService
    {
        /// <summary>
        /// Create a query in the given project with the given inputs.
        /// </summary>
        /// <param name="name">
        /// The name.
        /// </param>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="select">
        /// The select elements.
        /// </param>
        /// <param name="scope">
        /// The scope elements.
        /// </param>
        /// <param name="where">
        /// The where.
        /// </param>
        /// <param name="orderBy">
        /// The orderBy elements.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Query>> CreateQueryAsync(string name, Guid projectId, IReadOnlyList<string> select, IReadOnlyList<SysML2.NET.Common.IData> scope, Constraint where, IReadOnlyList<string> orderBy, CancellationToken cancellationToken);

        /// <summary>
        /// Delete the query with the given id (queryId) in the given project.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="queryId">
        /// The queryId.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Query>> DeleteQueryAsync(Guid projectId, Guid queryId, CancellationToken cancellationToken);

        /// <summary>
        /// Execute the given query in the owning project (Query.project) at the given commit. If the commit is
        /// not specified, then the head commit of the default branch of the project will be used.
        /// </summary>
        /// <param name="query">
        /// The query.
        /// </param>
        /// <param name="commitId">
        /// The identifier of the commit.
        /// </param>
        /// <param name="queryParameters">
        /// The paging parameters applied to the result.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<PagedResult<SysML2.NET.Common.IData>>> ExecuteQueryAsync(Query query, Guid? commitId, QueryParameters queryParameters, CancellationToken cancellationToken);

        /// <summary>
        /// Execute the query with the given id in the owning project (Query.project) at the given commit. If
        /// the commit is not specified, then the head commit of the default branch of the project will be used.
        /// </summary>
        /// <param name="queryId">
        /// The queryId.
        /// </param>
        /// <param name="commitId">
        /// The identifier of the commit.
        /// </param>
        /// <param name="queryParameters">
        /// The paging parameters applied to the result.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<PagedResult<SysML2.NET.Common.IData>>> ExecuteQueryByIdAsync(Guid queryId, Guid? commitId, QueryParameters queryParameters, CancellationToken cancellationToken);

        /// <summary>
        /// Get all the queries in the given project.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="queryParameters">
        /// The paging parameters applied to the result.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<PagedResult<Query>>> GetQueriesAsync(Guid projectId, QueryParameters queryParameters, CancellationToken cancellationToken);

        /// <summary>
        /// Get the query with the given id (queryId) in the given project.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="queryId">
        /// The queryId.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Query>> GetQueryByIdAsync(Guid projectId, Guid queryId, CancellationToken cancellationToken);

        /// <summary>
        /// Update the given query (updateQuery) in the given project.
        /// </summary>
        /// <param name="projectId">
        /// The identifier of the project.
        /// </param>
        /// <param name="updateQuery">
        /// The updateQuery.
        /// </param>
        /// <param name="cancellationToken">
        /// The <see cref="CancellationToken" /> that cancels the operation.
        /// </param>
        /// <returns>
        /// The outcome of the operation, or the errors that prevented it.
        /// </returns>
        Task<ErrorOr<Query>> UpdateQueryAsync(Guid projectId, Query updateQuery, CancellationToken cancellationToken);
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
