// <auto-generated />
// ------------------------------------------------------------------------------------------------
//  <copyright file="ICommitRepository.cs" company="Starion Group S.A.">
//
//    Copyright 2026 Starion Group S.A.
//    SPDX-License-Identifier: Apache-2.0
//
//  </copyright>
//  ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Fabric.ConcurrentServer.Persistence
{
    using System.CodeDom.Compiler;

    using SysML2.NET.PIM.DTO;

    /// <summary>
    /// Defines the persistence contract of the <see cref="Commit" /> records of the OMG Systems Modeling API and Services specification, §7.1.2.
    /// </summary>
    [GeneratedCode("Mycelium.SDK", "latest")]
    public partial interface ICommitRepository : IRecordRepository<Commit>
    {
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
