<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
        <LangVersion>14.0</LangVersion>
        <Version>0.0.1</Version>
        <Description>Enumeration providers and extension methods for the Mycelium SDK.</Description>
        <PackageId>Mycelium.SDK.Extensions</PackageId>
        <Company>Starion Group S.A.</Company>
        <Copyright>Copyright © Starion Group S.A.</Copyright>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/mycelium-cmbse/mycelium-sdk.git</RepositoryUrl>
        <RepositoryType>Git</RepositoryType>
        <Authors>Sam Gerene, Antoine Théate, Régis André, Tanase-Marius Manafu, Omrane Haj Mohamed</Authors>
        <RequireLicenseAcceptance>true</RequireLicenseAcceptance>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <GenerateSBOM>true</GenerateSBOM>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Mycelium.SDK\Mycelium.SDK.csproj" />
        <PackageReference Include="Microsoft.Sbom.Targets" Version="4.1.5" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
